name: Molecule Test all

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.7.9]

    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update pip
        run: |
          python -m pip install --upgrade pip

      - name: Set up virtualenv
        run: |
          pip3 install virtualenv
          virtualenv --python=python${{ matrix.python-version }} benchmark
          source benchmark/bin/activate
          pip install -r requirements.txt

      - name: Install ansible dependencies
        run: |
          source benchmark/bin/activate
          ansible-galaxy install cloudalchemy.node_exporter
          ansible-galaxy install cloudalchemy.prometheus

      - name: Install jq
        run: sudo apt-get install jq

      - name: Test with molecule
        run: make molecule_dryrun_all